Repository Team-MCToolkit/MCToolkit, pull requests merged in 2020-12, with the labels that each got.

#129 Move potion items in a new mod element
  .idea/copyright/MCreator.xml
  .idea/copyright/MCreator__EPL_exception_.xml
  .idea/copyright/MCreator__templates_.xml
  .idea/copyright/profiles_settings.xml
  plugins/generator-1.15.2/forge-1.15.2/mappings/potions.yaml
  plugins/generator-1.15.2/forge-1.15.2/potion.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/potionitem.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/potion.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/potionitem.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/potionitem.definition.yaml
  plugins/generator-1.16.4/forge-1.16.4/templates/potion.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/potionitem.java.ftl
  plugins/mcreator-localization/help/default/potionitem/display_name.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeRegistry.java
  src/main/java/net/mcreator/element/parts/EffectEntry.java
  src/main/java/net/mcreator/element/types/Potion.java
  src/main/java/net/mcreator/element/types/PotionItem.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionListEntry.java
  src/main/java/net/mcreator/ui/modgui/PotionGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionItemGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: improvement/modification, new feature, review requested

#127 Removed "What's next" option and modified stuff
  .github/FUNDING.yml
  .github/support.yml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/dialogs/workspace/WorkspaceGeneratorSetupDialog.java
Labels: improvement/modification

#128 Improved GUI Editor
  src/main/resources/net/mcreator/ui/res/guieditor.png
Labels: improvement/modification, review requested

#137 Ported all new block bases (#3 and #54) to 1.16.4
  plugins/generator-1.16.4/forge-1.16.4/block.definition.yaml
  plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/block_model_tbs.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/button.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/button_inventory.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/button_item.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/button_pressed.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/button_states.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice1.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice2.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice3.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice4.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice5.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_slice6.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/cake_states.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/honey.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/lever.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/lever_on.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/lever_states.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/pressure_plate.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/pressure_plate_down.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/pressure_plate_states.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/slime.json.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/json/txblock/txblock_item.json.ftl
Labels: official, review requested

#135 Updated installers
  LICENSE-header.txt
  build.gradle
  platform/export.gradle
  platform/linux/mcreator.sh
  platform/mac/Info.plist
  platform/mac/mac.gradle
  platform/mac/mcreator
  platform/windows/installer/install.nsi
  platform/windows/windows.gradle
Labels: improvement/modification, review requested

#136 Added 3 APIs to MCToolkit's core
  plugins/mcreator-core/apis/curios.yaml
  plugins/mcreator-core/apis/just_enough_items.yaml
  plugins/mcreator-core/apis/patchouli.yaml
Labels: new feature, official

#131 Support for blockstate variable/dependency type
  plugins/generator-1.15.2/forge-1.15.2/mappings/types.yaml
  plugins/generator-1.15.2/forge-1.15.2/procedures/_get_variable.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/_procedure_retval.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/_return.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/_set_variable.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/modbase/variableslist.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/mappings/types.yaml
  plugins/generator-1.16.4/forge-1.16.4/procedures/_get_variable.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/_procedure_retval.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/_return.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/_set_variable.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/modbase/variableslist.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/utils/procedures.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/Dependency.java
  src/main/java/net/mcreator/blockly/java/BlocklyVariables.java
  src/main/java/net/mcreator/blockly/java/JavaKeywordsMap.java
  src/main/java/net/mcreator/blockly/java/ProcedureTemplateIO.java
  src/main/java/net/mcreator/blockly/java/blocks/CustomDependencyBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureRetvalBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/ReturnBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVariables.java
  src/main/java/net/mcreator/workspace/elements/VariableElementType.java
  src/main/resources/blockly/js/mcreator_blocks.js
  src/main/resources/blockly/toolbox_procedure.xml
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature, review requested

#169 Port item modifications to 1.16.4
  plugins/generator-1.15.2/forge-1.15.2/templates/item.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/tooltips/has_alt_down.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/tooltips/has_control_down.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/tooltips/has_shift_down.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/tooltips/literal_text.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/tooltips/translatable_text.java.ftl
Labels: help wanted, improvement/modification, review requested

#187 (Re)Added Potion Effect in-app tips
  plugins/mcreator-localization/help/default/potioneffect/bad.md
  plugins/mcreator-localization/help/default/potioneffect/benefitical.md
  plugins/mcreator-localization/help/default/potioneffect/color.md
  plugins/mcreator-localization/help/default/potioneffect/effect_display_name.md
  plugins/mcreator-localization/help/default/potioneffect/icon.md
  plugins/mcreator-localization/help/default/potioneffect/instant.md
  plugins/mcreator-localization/help/default/potioneffect/render_in_hud.md
  plugins/mcreator-localization/help/default/potioneffect/render_in_inventory.md
  plugins/mcreator-localization/help/default/potioneffect/when_active_tick.md
  plugins/mcreator-localization/help/default/potioneffect/when_potion_applied.md
  plugins/mcreator-localization/help/default/potioneffect/when_potion_expires.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/bad.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/benefitical.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/color.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/effect_display_name.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/icon.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/instant.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/render_in_hud.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/render_in_inventory.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/when_active_tick.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/when_potion_applied.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/when_potion_expires.md
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
Labels: review requested

#195 Custom sounds new block option
  .gitignore
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
  plugins/mcreator-localization/help/default/common/soundtypes/break_sound.md
  plugins/mcreator-localization/help/default/common/soundtypes/fall_sound.md
  plugins/mcreator-localization/help/default/common/soundtypes/hit_sound.md
  plugins/mcreator-localization/help/default/common/soundtypes/place_sound.md
  plugins/mcreator-localization/help/default/common/soundtypes/step_sound.md
  plugins/mcreator-localization/help/fr_FR/common/soundtypes/break_sound.md
  plugins/mcreator-localization/help/fr_FR/common/soundtypes/fall_sound.md
  plugins/mcreator-localization/help/fr_FR/common/soundtypes/hit_sound.md
  plugins/mcreator-localization/help/fr_FR/common/soundtypes/place_sound.md
  plugins/mcreator-localization/help/fr_FR/common/soundtypes/step_sound.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, review requested

#194 Building tool pack maker
  plugins/mcreator-core/tools/packmakers/wood_pack.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/MainToolBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/dialogs/tools/BuildingPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/util/RecipeUtils.java
  src/main/java/net/mcreator/ui/laf/renderer/WTextureComboBoxRenderer.java
  src/main/resources/net/mcreator/ui/res/16px/buildpack.png
  src/main/resources/net/mcreator/ui/res/16px/woodpack.png
Labels: new feature, review requested

#201 Added support for Time variable and dependency
  plugins/generator-1.15.2/forge-1.15.2/procedures/_set_variable.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_day.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_hour.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_minute.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_month.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_second.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_time.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_year.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_to_string.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/_set_variable.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_day.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_hour.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_minute.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_month.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_second.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_time.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_year.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_to_string.ftl
  plugins/mcreator-core/procedures/time_get_day.json
  plugins/mcreator-core/procedures/time_get_hour.json
  plugins/mcreator-core/procedures/time_get_minute.json
  plugins/mcreator-core/procedures/time_get_month.json
  plugins/mcreator-core/procedures/time_get_second.json
  plugins/mcreator-core/procedures/time_get_time.json
  plugins/mcreator-core/procedures/time_get_year.json
  plugins/mcreator-core/procedures/time_to_string.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/ExternalBlockLoader.java
  src/main/java/net/mcreator/blockly/java/BlocklyVariables.java
  src/main/java/net/mcreator/blockly/java/JavaKeywordsMap.java
  src/main/java/net/mcreator/blockly/java/ProcedureTemplateIO.java
  src/main/java/net/mcreator/blockly/java/blocks/CustomDependencyBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureRetvalBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/ReturnBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/workspace/elements/VariableElementType.java
  src/main/resources/blockly/js/mcreator_blocks.js
  src/main/resources/blockly/toolbox_procedure.xml
Labels: new feature, review requested
