Repository Team-MCToolkit/MCToolkit, pull requests merged in 2020-11, with the labels that each got.

#3 New block bases
  plugins/generator-1.15.2/forge-1.15.2/block.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/block_model_tbs.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/button.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/button_inventory.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/button_item.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/button_pressed.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/button_states.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice1.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice2.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice3.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice4.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice5.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_slice6.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/cake_states.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_down.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_item.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_states.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-localization/lang/texts_vi_VN.properties
  plugins/mcreator-localization/lang/texts_zh_CN.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: new feature, official

#54 Lever, Slime and Honey block bases
  plugins/generator-1.15.2/forge-1.15.2/block.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/honey.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/lever.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/lever_on.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/lever_states.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/slime.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/txblock_item.json.ftl
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: new feature

#75 Fixed "Call procedure and get return value" blocks not working anymore
  plugins/generator-1.14.4/forge-1.14.4/procedures/_procedure_retval.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/_procedure_retval.java.ftl
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureRetvalBlock.java
Labels: bug

#99 Custom pack maker tools for plugins
  .idea/misc.xml
  plugins/mcreator-core/tools/packmakers/icons/toolpack.png
  plugins/mcreator-core/tools/packmakers/icons/woodpack.png
  plugins/mcreator-core/tools/packmakers/tool_pack.json
  plugins/mcreator-core/tools/packmakers/wood_pack.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/MainToolBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/dialogs/tools/MaterialPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/CustomPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/PackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/PackMakerToolIcons.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/PackMakerToolLoader.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/elements/Blocks.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/elements/Items.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/elements/Recipes.java
  src/main/java/net/mcreator/ui/dialogs/tools/plugin/elements/Tags.java
  src/main/java/net/mcreator/ui/dialogs/tools/util/RecipeUtils.java
  src/test/java/net/mcreator/integration/TestSetup.java
Labels: new feature, review requested

#122 Save grid settings for GUI
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/ui/modgui/CustomGUIGUI.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
Labels: new feature, review requested

#124 Added better RNG procedures
  plugins/generator-1.15.2/forge-1.15.2/procedures/random_boolean.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/random_gaussian.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/random_integer.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/random_boolean.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/random_gaussian.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/random_integer.java.ftl
  plugins/mcreator-core/procedures/random_boolean.json
  plugins/mcreator-core/procedures/random_gaussian.json
  plugins/mcreator-core/procedures/random_integer.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, review requested
