Repository Team-MCToolkit/MCToolkit, pull requests merged in 2021-01, with the labels that each got.

#204 Some fixes and improvements for Time variables
  plugins/generator-1.15.2/forge-1.15.2/mappings/types.yaml
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_current_time.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_date.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_get_year.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/time_to_string.ftl
  plugins/generator-1.16.4/forge-1.16.4/mappings/types.yaml
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_current_time.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_date.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_get_year.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/time_to_string.ftl
  plugins/mcreator-core/procedures/time_get_current_time.json
  plugins/mcreator-core/procedures/time_get_date.json
  plugins/mcreator-core/procedures/time_get_day.json
  plugins/mcreator-core/procedures/time_get_hour.json
  plugins/mcreator-core/procedures/time_get_minute.json
  plugins/mcreator-core/procedures/time_get_month.json
  plugins/mcreator-core/procedures/time_get_second.json
  plugins/mcreator-core/procedures/time_get_time.json
  plugins/mcreator-core/procedures/time_get_year.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/Dependency.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: bug, improvement/modification, review requested

#203 Reload plugins button
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/action/impl/ReloadPlugins.java
Labels: new feature, review requested

#213 Splash texts
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/resources/net/mcreator/ui/texts/splashes.txt
Labels: new feature, review requested

#215 Fix for #212
  src/main/java/net/mcreator/ui/dialogs/TextureFolderDialog.java
Labels: bug

#153 Modify Potion Effect and Potion Item mod elements previews
  plugins/generator-1.15.2/forge-1.15.2/generator.yaml
  plugins/generator-1.16.4/forge-1.16.4/generator.yaml
  plugins/generator-addon-1.16.x/addon-1.16.x/generator.yaml
  plugins/generator-resourcepack-1.16.x/resourcepack-1.16.x/generator.yaml
  src/main/java/net/mcreator/element/ModElementTypeRegistry.java
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/element/types/PotionItem.java
  src/main/java/net/mcreator/workspace/WorkspaceFolderManager.java
Labels: improvement/modification, review requested

#197 New Redstone Emittion condition for Redstone Properties
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/procedures.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/utils/procedures.java.ftl
  plugins/mcreator-localization/help/default/block/redstone_condition.md
  plugins/mcreator-localization/help/fr_FR/block/redstone_condition.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/StructureGenGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: help wanted, improvement/modification
